name: news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  dio: 5.1.1
  bloc: ^8.1.0
  get_it: 7.2.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  shared_preferences: 2.0.17
  shimmer: 2.0.0
  cached_network_image: ^3.3.0
  intl: 0.17.0
  webview_flutter: ^3.0.4
  go_router: ^9.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/